# Generated by Django 2.2.10 on 2021-09-11 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('propertyName', models.CharField(max_length=200, verbose_name='Property Name')),
                ('propertyType', models.CharField(choices=[('Flat', 'Flat'), ('Apartment', 'Apartment'), ('Home', 'Home'), ('Office Space', 'Office Space'), ('Showrooms/Bulky Goods', 'Showrooms/Bulky Goods'), ('Commercial Building', 'Commercial Building')], default='Flat', max_length=30, verbose_name='Property Type')),
                ('propertyImage', models.ImageField(default='image.jpg', upload_to='images/')),
                ('slug', models.SlugField(max_length=255, verbose_name='Slug / URL')),
                ('email', models.CharField(max_length=128, null=True, verbose_name='Email')),
                ('contactNo', models.CharField(max_length=25, verbose_name='Contact No')),
                ('streetAddress', models.CharField(max_length=200, verbose_name='Street Address')),
                ('city', models.CharField(max_length=200, verbose_name='City')),
                ('state', models.CharField(choices=[('AU-NSW', 'New South Wales'), ('AU-QLD', 'Queensland'), ('AU-SA', 'South Australia'), ('AU-TAS', 'Tasmania'), ('AU-VIC', 'Victoria'), ('AU-WA', 'Western Australia')], default='', max_length=150, verbose_name='State')),
                ('price', models.IntegerField(verbose_name='Price')),
                ('priceOption', models.CharField(max_length=200, verbose_name='Pricing Model')),
                ('useOptions', models.CharField(choices=[('Rent', 'Rent'), ('Share', 'Share'), ('Buy', 'Buy'), ('Sell', 'Sell'), ('Lease', 'Lease'), ('Business Purpose', 'Business Purpose'), ('General', 'General')], default='Not Urgent', max_length=40, verbose_name='Use Options')),
                ('additionalInfo', models.TextField(blank=True, null=True, verbose_name='Additional Information')),
                ('landAreaApprox', models.IntegerField(verbose_name='Land Area Approx (sqm)')),
                ('floorAreaApprox', models.IntegerField(verbose_name='Floor Area Approx (sqm)')),
                ('noOfBedrooms', models.IntegerField(verbose_name='No of BedRoom')),
                ('noOfKitchen', models.IntegerField(verbose_name='No of Kitchen')),
                ('noOfHall', models.IntegerField(verbose_name='No of Hall')),
                ('noOfBathrooms', models.IntegerField(verbose_name='No of Bathroom')),
                ('parking', models.IntegerField(verbose_name='No of Parking')),
                ('amenities', models.TextField(blank=True, null=True, verbose_name='Features & Amenities')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('addedOn', models.DateTimeField(auto_now_add=True, verbose_name='Added Date')),
                ('isActive', models.BooleanField(default=True, verbose_name='Is Active')),
                ('isFeatured', models.BooleanField(default=True, verbose_name='Is Featured')),
            ],
        ),
    ]
