# Generated by Django 2.2.10 on 2021-09-11 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='propertyType',
            field=models.CharField(choices=[('Flat', 'Flat'), ('Apartment', 'Apartment'), ('Home', 'Home'), ('OfficeSpace', 'Office Space'), ('Showrooms-Bulky-Goods', 'Showrooms/Bulky Goods'), ('Commercial-Building', 'Commercial Building')], default='Flat', max_length=30, verbose_name='Property Type'),
        ),
        migrations.AlterField(
            model_name='property',
            name='useOptions',
            field=models.CharField(choices=[('Rent', 'Rent'), ('Share', 'Share'), ('Buy', 'Buy'), ('Sell', 'Sell'), ('Lease', 'Lease'), ('Business-Purpose', 'Business Purpose'), ('General', 'General')], default='Not Urgent', max_length=40, verbose_name='Use Options'),
        ),
    ]
