# Generated by Django 2.2.10 on 2021-09-12 03:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0002_auto_20210911_2003'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('customerid', models.AutoField(primary_key=True, serialize=False)),
                ('fname', models.CharField(blank=True, max_length=50, null=True)),
                ('lname', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.CharField(blank=True, max_length=50, null=True)),
                ('telephone', models.CharField(blank=True, max_length=10, null=True)),
                ('streetadd', models.CharField(blank=True, max_length=50, null=True)),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('country', models.CharField(blank=True, max_length=50, null=True)),
                ('zip', models.CharField(blank=True, max_length=5, null=True)),
                ('profileImage', models.ImageField(default='user.jpg', upload_to='images/')),
                ('coverImage', models.ImageField(default='cover.jpg', upload_to='images/')),
                ('slug', models.SlugField(max_length=255, verbose_name='Slug / URL')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
            ],
            options={
                'db_table': 'customers',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('orderid', models.AutoField(primary_key=True, serialize=False)),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('entrydate', models.DateTimeField(blank=True, null=True)),
                ('shipped', models.CharField(blank=True, max_length=1, null=True)),
            ],
            options={
                'db_table': 'orders',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=200, verbose_name='Full Name')),
                ('age', models.IntegerField()),
                ('email', models.CharField(max_length=128, null=True, verbose_name='Email')),
                ('contactNo', models.CharField(max_length=30, verbose_name='Contact No')),
                ('urgency', models.CharField(choices=[('Urgent', 'Urgent'), ('Moderate', 'Moderate'), ('Not Urgent', 'Not Urgent')], default='Not Urgent', max_length=40, verbose_name='Urgency')),
                ('additionalInfo', models.TextField(blank=True, null=True, verbose_name='Additional Information')),
                ('requestOn', models.DateTimeField(auto_now_add=True, verbose_name='Request Date')),
                ('seenStatus', models.BooleanField(default=False, verbose_name='Seen Status')),
                ('action_status', models.CharField(blank=True, choices=[('Request Received', 'Request Received'), ('Waiting', 'Waiting'), ('Under Approval', 'Under Approval'), ('Cancelled', 'Cancelled'), ('Approved', 'Approved'), ('Unspecified', 'Unspecified')], default='Receive', max_length=200, verbose_name='Plasma Donate')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
