# Generated by Django 2.2.10 on 2021-09-17 13:01

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0004_auto_20210913_0631'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Request',
            new_name='BookNow',
        ),
    ]
