# Generated by Django 2.2.10 on 2021-09-17 13:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0006_auto_20210917_1916'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booknow',
            name='user',
        ),
        migrations.AddField(
            model_name='booknow',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
