# Generated by Django 2.2.10 on 2021-09-17 13:43

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0007_auto_20210917_1923'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BookNow',
            new_name='Booking',
        ),
    ]
