# Generated by Django 2.2.10 on 2021-09-17 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20210917_1928'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customers',
            options={},
        ),
    ]
