# Generated by Django 2.2.10 on 2021-09-17 14:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0009_auto_20210917_2028'),
    ]

    operations = [
        migrations.AddField(
            model_name='customers',
            name='userid',
            field=models.ForeignKey(blank=True, db_column='id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterModelTable(
            name='customers',
            table=None,
        ),
    ]
