# Generated by Django 2.2.10 on 2021-09-17 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20210917_2030'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orders',
            options={},
        ),
    ]
