# Generated by Django 2.2.10 on 2021-09-18 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20210917_2031'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='age',
        ),
        migrations.AddField(
            model_name='booking',
            name='address',
            field=models.CharField(default='-', max_length=255, verbose_name='Address'),
        ),
        migrations.AddField(
            model_name='orders',
            name='customer',
            field=models.ForeignKey(blank=True, db_column='customerid', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.Customers'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='contactNo',
            field=models.CharField(default='-', max_length=30, verbose_name='Contact No'),
        ),
        migrations.AlterModelTable(
            name='orders',
            table=None,
        ),
    ]
