# Generated by Django 2.2.10 on 2021-05-07 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RequestBed',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('full_name', models.TextField(max_length=100)),
                ('age', models.IntegerField()),
                ('gender', models.TextField(max_length=6)),
                ('contactNo', models.TextField()),
                ('streetAddress', models.TextField(max_length=200)),
                ('city', models.TextField(max_length=100)),
                ('state', models.TextField(blank=True)),
                ('bedsQty', models.IntegerField()),
                ('urgency', models.IntegerField()),
                ('additionalInfo', models.TextField()),
                ('o_name', models.TextField(max_length=100)),
                ('o_contactNo', models.TextField(max_length=20)),
                ('o_address', models.TextField(max_length=200)),
                ('o_relation', models.TextField()),
                ('requestDate', models.DateField()),
                ('seenStatus', models.BooleanField(default=False)),
            ],
        ),
    ]
