# Generated by Django 2.2.10 on 2021-05-07 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid19', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestbed',
            name='city',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='requestbed',
            name='contactNo',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='requestbed',
            name='full_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='requestbed',
            name='gender',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='requestbed',
            name='o_address',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='requestbed',
            name='o_contactNo',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='requestbed',
            name='o_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='requestbed',
            name='o_relation',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='requestbed',
            name='state',
            field=models.CharField(blank=True, max_length=6),
        ),
        migrations.AlterField(
            model_name='requestbed',
            name='streetAddress',
            field=models.CharField(max_length=200),
        ),
    ]
