# Generated by Django 2.2.10 on 2021-05-07 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid19', '0003_auto_20210507_1414'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestbed',
            name='bedType',
            field=models.CharField(choices=[('ICU', 'ICU'), ('Normal', 'Normal'), ('Isolation', 'Isolation'), ('Ventilator', 'Ventilator'), ('Unspecified', 'Unspecified')], default='Normal', max_length=20),
        ),
    ]
