# Generated by Django 2.2.10 on 2021-05-07 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid19', '0004_requestbed_bedtype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestbed',
            name='additionalInfo',
            field=models.TextField(verbose_name='Additional Information'),
        ),
        migrations.AlterField(
            model_name='requestbed',
            name='bedType',
            field=models.CharField(choices=[('ICU', 'ICU'), ('Normal', 'Normal'), ('Isolation', 'Isolation'), ('Ventilator', 'Ventilator'), ('Unspecified', 'Unspecified')], default='Normal', max_length=20, verbose_name='Bed Type'),
        ),
        migrations.AlterField(
            model_name='requestbed',
            name='bedsQty',
            field=models.IntegerField(verbose_name='No of Beds'),
        ),
        migrations.AlterField(
            model_name='requestbed',
            name='city',
            field=models.CharField(max_length=100, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='requestbed',
            name='contactNo',
            field=models.CharField(max_length=15, verbose_name='Contact No'),
        ),
        migrations.AlterField(
            model_name='requestbed',
            name='full_name',
            field=models.CharField(max_length=100, verbose_name='Full Name'),
        ),
        migrations.AlterField(
            model_name='requestbed',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='Other', max_length=1, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='requestbed',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='requestbed',
            name='requestDate',
            field=models.DateField(verbose_name='Request Date'),
        ),
        migrations.AlterField(
            model_name='requestbed',
            name='seenStatus',
            field=models.BooleanField(default=False, verbose_name='Seen Status'),
        ),
        migrations.AlterField(
            model_name='requestbed',
            name='state',
            field=models.CharField(choices=[('AU-NSW', 'New South Wales'), ('AU-QLD', 'Queensland'), ('AU-SA', 'South Australia'), ('AU-TAS', 'Tasmania'), ('AU-VIC', 'Victoria'), ('AU-WA', 'Western Australia')], default='', max_length=30, verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='requestbed',
            name='streetAddress',
            field=models.CharField(max_length=200, verbose_name='Street Address'),
        ),
        migrations.AlterField(
            model_name='requestbed',
            name='urgency',
            field=models.CharField(choices=[('Urgent', 'Urgent'), ('Moderate', 'Moderate'), ('Not Urgent', 'Not Urgent')], default='Not Urgent', max_length=10, verbose_name='Urgency'),
        ),
    ]
