# Generated by Django 2.2.10 on 2021-05-08 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid19', '0005_auto_20210507_2305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestbed',
            name='additionalInfo',
            field=models.TextField(blank=True, null=True, verbose_name='Additional Information'),
        ),
        migrations.AlterField(
            model_name='requestbed',
            name='o_address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='requestbed',
            name='o_contactNo',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='requestbed',
            name='o_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='requestbed',
            name='o_relation',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
