# Generated by Django 2.2.10 on 2021-05-08 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid19', '0006_auto_20210508_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestbed',
            name='requestDate',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Request Date'),
        ),
    ]
