# Generated by Django 2.2.10 on 2021-05-08 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid19', '0008_donateplasma'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donateplasma',
            old_name='donor_age',
            new_name='age',
        ),
        migrations.RenameField(
            model_name='donateplasma',
            old_name='donor_city',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='donateplasma',
            old_name='donor_contactNo',
            new_name='contactNo',
        ),
        migrations.RenameField(
            model_name='donateplasma',
            old_name='donor_name',
            new_name='full_name',
        ),
        migrations.RenameField(
            model_name='donateplasma',
            old_name='donor_gender',
            new_name='gender',
        ),
        migrations.RenameField(
            model_name='donateplasma',
            old_name='donor_state',
            new_name='state',
        ),
        migrations.RenameField(
            model_name='donateplasma',
            old_name='donor_streetAddress',
            new_name='streetAddress',
        ),
        migrations.RenameField(
            model_name='requestbed',
            old_name='requestDate',
            new_name='requestOn',
        ),
        migrations.AddField(
            model_name='donateplasma',
            name='action_status',
            field=models.CharField(choices=[('', 'Please Select'), ('Request Received', 'Request Received'), ('Waiting', 'Waiting'), ('Looking for Donor', 'Looking for Donor'), ('Under Approval', 'Under Approval'), ('Transfer in Progress', 'Transfer in Progress'), ('Cancelled', 'Cancelled'), ('Approved', 'Approved'), ('Patient Expired', 'Patient Expired'), ('Donor Does not Fit', 'Donor Does not Fit'), ('Request More', 'Request More')], default='Receive', max_length=10, verbose_name='Plasma Donate'),
        ),
        migrations.AddField(
            model_name='requestbed',
            name='action_status',
            field=models.CharField(choices=[('Solved', 'Solved'), ('Request Received', 'Request Received'), ('Waiting', 'Waiting'), ('Under Approval', 'Under Approval'), ('Cancelled', 'Cancelled'), ('Approved', 'Approved'), ('Patient Expired', 'Patient Expired'), ('Not available', 'Not available'), ('Still Finding', 'Still Finding')], default='Receive', max_length=10, verbose_name='Plasma Donate'),
        ),
        migrations.AlterField(
            model_name='donateplasma',
            name='donor_option',
            field=models.CharField(choices=[('Receive', 'I am Looking for Plasma Donor'), ('Donate', 'I want to donate Plasma')], default='Receive', max_length=10, verbose_name='Plasma Donate'),
        ),
    ]
