# Generated by Django 2.2.10 on 2021-05-08 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid19', '0010_auto_20210508_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donateplasma',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='Other', max_length=10, verbose_name='Gender'),
        ),
    ]
