# Generated by Django 2.2.10 on 2021-05-13 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid19', '0012_otherrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='donateplasma',
            name='email',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='requestbed',
            name='email',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='donateplasma',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='Other', max_length=10, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='requestbed',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='Other', max_length=1, verbose_name='Gender'),
        ),
    ]
