# Generated by Django 2.2.10 on 2021-05-13 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid19', '0014_auto_20210513_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donateplasma',
            name='state',
            field=models.CharField(choices=[('AU-NSW', 'New South Wales'), ('AU-QLD', 'Queensland'), ('AU-SA', 'South Australia'), ('AU-TAS', 'Tasmania'), ('AU-VIC', 'Victoria'), ('AU-WA', 'Western Australia')], default='', max_length=50, verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='otherrequest',
            name='contactNo',
            field=models.CharField(max_length=30, verbose_name='Contact No'),
        ),
        migrations.AlterField(
            model_name='otherrequest',
            name='state',
            field=models.CharField(choices=[('AU-NSW', 'New South Wales'), ('AU-QLD', 'Queensland'), ('AU-SA', 'South Australia'), ('AU-TAS', 'Tasmania'), ('AU-VIC', 'Victoria'), ('AU-WA', 'Western Australia')], default='', max_length=50, verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='requestbed',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='Other', max_length=10, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='requestbed',
            name='urgency',
            field=models.CharField(choices=[('Urgent', 'Urgent'), ('Moderate', 'Moderate'), ('Not Urgent', 'Not Urgent')], default='Not Urgent', max_length=40, verbose_name='Urgency'),
        ),
    ]
