# Generated by Django 2.2.10 on 2021-05-13 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid19', '0015_auto_20210513_2128'),
    ]

    operations = [
        migrations.AddField(
            model_name='otherrequest',
            name='urgency',
            field=models.CharField(choices=[('Urgent', 'Urgent'), ('Moderate', 'Moderate'), ('Not Urgent', 'Not Urgent')], default='Not Urgent', max_length=40, verbose_name='Urgency'),
        ),
        migrations.AlterField(
            model_name='otherrequest',
            name='action_status',
            field=models.CharField(blank=True, choices=[('Request Received', 'Request Received'), ('Waiting', 'Waiting'), ('Under Approval', 'Under Approval'), ('Cancelled', 'Cancelled'), ('Approved', 'Approved'), ('Unspecified', 'Unspecified')], default='Receive', max_length=200, verbose_name='Plasma Donate'),
        ),
    ]
